import Link from 'next/link';

const NAV_LINKS = ['Dashboard', 'Predictions', 'Portfolio', 'News'] as const;

export function Footer() {
  return (
    <footer className="fixed bottom-0 left-0 right-0 h-20 bg-background border-t border-border z-50">
      <div className="max-w-[1440px] mx-auto h-full px-6 flex flex-col justify-between py-3">

        {/* Top row: identity · nav · stack */}
        <div className="flex items-center justify-between">

          <div className="flex items-center gap-2">
            <span className="font-bold text-sm italic text-golden tracking-tight">stoX</span>
            <span className="text-border text-xs">·</span>
            <span className="text-xs text-muted-foreground">
              ML-powered S&amp;P SL20 prediction engine
            </span>
            <span className="text-border text-xs">·</span>
            <span className="text-xs text-muted-foreground">
              Colombo Stock Exchange
            </span>
          </div>

          <nav className="flex items-center gap-5">
            {NAV_LINKS.map((page) => (
              <Link
                key={page}
                href={`/${page.toLowerCase()}`}
                className="text-xs text-muted-foreground hover:text-golden transition-colors"
              >
                {page}
              </Link>
            ))}
          </nav>

          <div className="flex items-center gap-2 text-xs text-muted-foreground">
            <span>Next.js 14</span>
            <span className="text-border">·</span>
            <span>Recharts</span>
            <span className="text-border">·</span>
            <span>Zustand</span>
            <span className="text-border">·</span>
            <span>shadcn/ui</span>
          </div>

        </div>

        {/* Bottom row: legal disclaimer */}
        <p className="text-[10px] text-muted-foreground/50 text-center leading-tight">
          stoX is a research &amp; demonstration project. Predictions are generated by an ML model and do
          not constitute financial advice. Paper trading uses virtual capital only. Past performance does
          not indicate future results. Data shown is simulated for development purposes.
        </p>

      </div>
    </footer>
  );
}
